### ISSUE TITLE
Bot not working

### ISSUE THREAD

**Issue by D3G3Nerator** [MorrisWin86/pancakeswap_sniper#1]
t [SequelizeConnectionError]: password authentication failed for user "postgres"
    at h._connectionCallback (C:\users\victo\pancakeswap_sniper\build\app.js:2:2057299)
    at h._handleErrorWhileConnecting (C:\users\victo\pancakeswap_sniper\build\app.js:2:1787632)
    at h._handleErrorMessage (C:\users\victo\pancakeswap_sniper\build\app.js:2:1787881)
    at e.exports.emit (node:events:376:20)
    at C:\users\victo\pancakeswap_sniper\build\app.js:2:1796121
    at t.Parser.parse (C:\users\victo\pancakeswap_sniper\build\app.js:2:1770016)
    at Socket.<anonymous> (C:\users\victo\pancakeswap_sniper\build\app.js:2:1766696)
    at Socket.emit (node:events:376:20)
    at addChunk (node:internal/streams/readable:311:12)
    at readableAddChunk (node:internal/streams/readable:286:9)
    at Socket.Readable.push (node:internal/streams/readable:225:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:192:23) {
  parent: error: password authentication failed for user "postgres"
      at t.Parser.parseErrorMessage (C:\users\victo\pancakeswap_sniper\build\app.js:2:1774730)
      at t.Parser.handlePacket (C:\users\victo\pancakeswap_sniper\build\app.js:2:1771368)
      at t.Parser.parse (C:\users\victo\pancakeswap_sniper\build\app.js:2:1770023)
      at Socket.<anonymous> (C:\users\victo\pancakeswap_sniper\build\app.js:2:1766696)
      at Socket.emit (node:events:376:20)
      at addChunk (node:internal/streams/readable:311:12)
      at readableAddChunk (node:internal/streams/readable:286:9)
      at Socket.Readable.push (node:internal/streams/readable:225:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:192:23) {
    length: 166,
    severity: 'FATAL',
    code: '28P01',
    detail: undefined,
    hint: undefined,
    position: undefined,
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'd:\\pginstaller_13.auto\\postgres.windows-x64\\src\\backend\\libpq\\auth.c',
    line: '334',
    routine: 'auth_failed'
  },
  original: error: password authentication failed for user "postgres"
      at t.Parser.parseErrorMessage (C:\users\victo\pancakeswap_sniper\build\app.js:2:1774730)
      at t.Parser.handlePacket (C:\users\victo\pancakeswap_sniper\build\app.js:2:1771368)
      at t.Parser.parse (C:\users\victo\pancakeswap_sniper\build\app.js:2:1770023)
      at Socket.<anonymous> (C:\users\victo\pancakeswap_sniper\build\app.js:2:1766696)
      at Socket.emit (node:events:376:20)
      at addChunk (node:internal/streams/readable:311:12)
      at readableAddChunk (node:internal/streams/readable:286:9)
      at Socket.Readable.push (node:internal/streams/readable:225:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:192:23) {
    length: 166,
    severity: 'FATAL',
    code: '28P01',
    detail: undefined,
    hint: undefined,
    position: undefined,
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'd:\\pginstaller_13.auto\\postgres.windows-x64\\src\\backend\\libpq\\auth.c',
    line: '334',
    routine: 'auth_failed'
  }
}

is this a postgres issue ?

**Comment by margin-hub** [comment]
error: password authentication failed for user "postgres"
-----------------
You need to set up a Postgres credential on the config file.
